spring:
  application:
    name: auth-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/hireflow
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 900000

refresh-token:
  expiration-seconds: 86400